#!/usr/bin/env python

import argparse
import json
import sys


def parse_pod_output():
    out = sys.stdin.readlines()
    foo = json.loads(' '.join(out))
    for item in foo['items']:
	if item['metadata']['name'] == 'fectrl-wrew6':
		if item['status']['phase'] == "Running":
			print item['status']['podIP']

if __name__ == "__main__":
        parse_pod_output()
