#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

echo "Installing kubernetes-node on $JUJU_UNIT_NAME"

function conditional_apt_update(){
    if expr $(date +%s) - $(stat -c %Y /var/lib/apt/periodic/update-success-stamp) > $0
    then
        apt-update -qq
    fi
}

conditional_apt_update 36000

apt-get install -q -y \
    bridge-utils \
    python-dev \
    python-pip \
    wget

pip install path.py

# Create the necessary kubernetes group.
groupadd -f kubernetes
useradd -d /var/lib/kubernetes \
    -g kubernetes \
    -s /sbin/nologin \
    --system \
    kubernetes \
    || true


install -d -m 0744 -o kubernetes -g kubernetes /var/lib/kubernetes
install -d -m 0744 -o kubernetes -g kubernetes /etc/kubernetes/manifests

# wait for the world, depends on where we installed it from distro
#sudo service docker.io stop
# or upstream archive
#sudo service docker stop
